// ============================================================================
// student/Dashboard.jsx
// ----------------------------------------------------------------------------
// WHAT THIS FILE IS: the entire STUDENT area — the biggest file in the project.
// A student can browse/download lessons, view a lesson's approved summaries,
// take teacher quizzes (timed), and create & take private "practice" quizzes
// generated by AI from their own documents.
//
// It's organized as many sub-page components, with a ROOT component at the
// bottom that swaps between them based on the active tab.
// ============================================================================

import { useState, useEffect, useRef } from 'react'
import { Sidebar, Topbar } from '../../components/layout/Layout'
import { useAuth } from '../../context/AuthContext'
import { useFetch } from '../../hooks/useFetch'
import { useHashPage } from '../../hooks/useHashPage'
import { lessonsAPI, summariesAPI, quizzesAPI, practiceQuizzesAPI } from '../../services/api'
import ChatPage from '../shared/ChatPage'                          // shared "chat with a PDF" screen
import MySummaries from './MySummaries'                            // the My Summaries tab (its own file)
import ConfirmDialog from '../../components/common/ConfirmDialog'

// Turn a lesson title into a safe download filename (strip odd characters).
const safeFilename = (name) => (name || 'lesson').replace(/[^\w\s.-]/g, '_').trim() || 'lesson'

// Pick a greeting based on the current hour of the day.
const greeting = () => {
  const h = new Date().getHours()
  if (h < 12) return 'Good morning'
  if (h < 17) return 'Good afternoon'
  return 'Good evening'
}

// ─── DASHBOARD HOME ──────────────────────────────────
// The landing tab: greeting, stat cards, recent lessons, and quick actions.
function StudentHome({ setPage, lessons, summaries, firstName }) {
  // Count summaries by status, to show on the stat cards.
  const approved = (summaries || []).filter(s => s.status === 'APPROVED').length
  const pending  = (summaries || []).filter(s => s.status === 'PENDING').length

  return (
    <div className="content">
      <div className="page-header">
        <div className="page-title">{greeting()}{firstName ? <>, <em>{firstName}</em></> : ''}</div>
        <div className="page-sub">Pick up where you left off.</div>
      </div>
      <div className="stats-grid">
        {[
          { icon: 'ti-books',     val: (lessons || []).length,   label: 'Available Lessons', page: 'student-browse' },
          { icon: 'ti-notebook',  val: (summaries || []).length, label: 'My Summaries',      page: 'student-summaries' },
          { icon: 'ti-check',     val: approved,                  label: 'Approved',          page: 'student-summaries' },
          { icon: 'ti-hourglass', val: pending,                   label: 'Pending Review',    page: 'student-summaries' },
        ].map((s) => (
          <button
            key={s.label}
            type="button"
            className="stat-card-btn"
            onClick={() => setPage(s.page)}
            aria-label={`${s.label}: ${s.val}. Open ${s.label}.`}
          >
            <div className="stat-card">
              <div className="stat-icon"><i className={`ti ${s.icon}`} aria-hidden="true" /></div>
              <div className="stat-value">{s.val}</div>
              <div className="stat-label">{s.label}</div>
              <div className="stat-hint">Open <i className="ti ti-arrow-right" aria-hidden="true" style={{ fontSize: 11 }} /></div>
            </div>
          </button>
        ))}
      </div>
      <div className="two-col">
        <div className="card">
          <div className="section-header">
            <div className="section-title">Recently Added</div>
            <button className="btn btn-neutral btn-sm" onClick={() => setPage('student-browse')}>
              Browse all <i className="ti ti-arrow-right" aria-hidden="true" />
            </button>
          </div>
          {(lessons || []).slice(0, 4).map((l, i) => (
            <div key={l.id} style={{ display: 'flex', alignItems: 'center', gap: 12, paddingBottom: 12, borderBottom: i < 3 ? '1px solid var(--border)' : 'none', marginBottom: i < 3 ? 12 : 0 }}>
              <div style={{ width: 38, height: 38, borderRadius: 10, background: 'var(--surface2)', border: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 16, color: 'var(--icon)', flexShrink: 0 }}>
                <i className={`ti ${l.fileType === 'PDF' ? 'ti-file-text' : l.fileType === 'DOCX' ? 'ti-file-description' : 'ti-presentation'}`} aria-hidden="true" />
              </div>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontSize: 13.5, fontWeight: 500, color: 'var(--text)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{l.title}</div>
                <div style={{ fontSize: 11, color: 'var(--text3)', marginTop: 3, letterSpacing: '0.04em' }}>{l.teacher?.firstName} {l.teacher?.lastName} · {l.module?.name}</div>
              </div>
              <button className="btn btn-neutral btn-sm" onClick={() => setPage('student-browse')}>View</button>
            </div>
          ))}
          {(!lessons || lessons.length === 0) && (
            <div className="empty-state" style={{ padding: '32px 16px' }}>
              <i className="ti ti-book-off empty-icon" aria-hidden="true" />
              <div className="empty-text">Nothing here yet. Lessons will appear as teachers share them.</div>
            </div>
          )}
        </div>
        <div className="card">
          <div className="section-title" style={{ marginBottom: 16 }}>Quick Actions</div>
          {[
            { icon: 'ti-search',         label: 'Browse Lessons',  sub: 'Find and download materials',       page: 'student-browse' },
            { icon: 'ti-checklist',      label: 'Take a Quiz',     sub: 'Quizzes assigned to your filière',   page: 'student-quizzes' },
            { icon: 'ti-sparkles',       label: 'Practice Quiz',   sub: 'Generate a private quiz from a PDF', page: 'student-practice' },
            { icon: 'ti-message-circle', label: 'Chat with PDF',   sub: 'Ask questions, get summaries',      page: 'student-chat' },
            { icon: 'ti-notebook',       label: 'My Summaries',    sub: 'View submitted summaries and status', page: 'student-summaries' },
          ].map((a) => (
            <button key={a.page} onClick={() => setPage(a.page)} style={{ display: 'flex', alignItems: 'center', gap: 14, padding: 14, background: 'transparent', border: '1px solid var(--border)', borderRadius: 10, cursor: 'pointer', transition: 'all 0.2s', textAlign: 'left', width: '100%', marginBottom: 10 }}
              onMouseEnter={e => { e.currentTarget.style.borderColor = 'var(--gold-border)'; e.currentTarget.style.background = 'var(--gold-dim)' }}
              onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.background = 'transparent' }}>
              <div style={{ width: 40, height: 40, borderRadius: 10, background: 'var(--gold-dim)', border: '1px solid var(--gold-border)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 18, color: 'var(--gold)', flexShrink: 0 }}>
                <i className={`ti ${a.icon}`} aria-hidden="true" />
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 14, fontWeight: 500, color: 'var(--text)' }}>{a.label}</div>
                <div style={{ fontSize: 12, color: 'var(--text3)', marginTop: 2 }}>{a.sub}</div>
              </div>
              <i className="ti ti-arrow-right" aria-hidden="true" style={{ color: 'var(--text3)', fontSize: 16 }} />
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}

// ─── BROWSE LESSONS ──────────────────────────────────
// A searchable, filterable grid of every lesson the student can access. Toggle
// chips let them scope the search to just teachers or just module names.
function BrowseLessons({ setPage, setSelectedLesson }) {
  const { data: lessons, loading } = useFetch(() => lessonsAPI.getAll())
  const [search, setSearch] = useState('')              // text in the search box
  const [moduleFilter, setModuleFilter] = useState('all')  // optional module-name filter
  const [filterTeachers, setFilterTeachers] = useState(false)  // limit search to teacher names
  const [filterModules, setFilterModules] = useState(false)    // limit search to module names

  // Build the visible list by applying the search text + filter toggles.
  const filtered = (lessons || []).filter(l => {
    const q = search.toLowerCase()
    const teacherName = `${l.teacher?.firstName || ''} ${l.teacher?.lastName || ''}`.toLowerCase()
    const moduleName = (l.module?.name || '').toLowerCase()
    const title = (l.title || '').toLowerCase()

    let matchSearch
    if (!q) {
      matchSearch = true
    } else if (filterTeachers && filterModules) {
      matchSearch = teacherName.includes(q) || moduleName.includes(q)
    } else if (filterTeachers) {
      matchSearch = teacherName.includes(q)
    } else if (filterModules) {
      matchSearch = moduleName.includes(q)
    } else {
      matchSearch = title.includes(q) || teacherName.includes(q) || moduleName.includes(q)
    }
    const matchModule = moduleFilter === 'all' || l.module?.name?.toLowerCase().includes(moduleFilter.toLowerCase())
    return matchSearch && matchModule
  })

  const chipStyle = (active) => ({
    display: 'inline-flex', alignItems: 'center', gap: 6,
    padding: '0 14px', height: 42, borderRadius: 10,
    fontSize: 13, fontWeight: 500, cursor: 'pointer',
    border: `1px solid ${active ? 'var(--gold)' : 'var(--border)'}`,
    background: active ? 'var(--gold-dim)' : 'transparent',
    color: active ? 'var(--gold)' : 'var(--text2)',
    transition: 'all 0.2s', whiteSpace: 'nowrap',
  })

  // Remember which lesson was clicked, then switch to the lesson-detail page.
  const openLesson = (l) => { setSelectedLesson(l); setPage('student-lesson') }

  // Download a lesson file. stopPropagation keeps the card's click (open) from
  // also firing when the user only meant to hit the Download button.
  const download = async (l, e) => {
    e.stopPropagation()
    try {
      const res = await lessonsAPI.download(l.id)
      const url = URL.createObjectURL(new Blob([res.data]))
      const a = document.createElement('a'); a.href = url
      a.download = `${safeFilename(l.title)}.${l.fileType.toLowerCase()}`; a.click()
      URL.revokeObjectURL(url)
    } catch (err) {
      // Silent fallback — user simply doesn't get a file. Could be elevated to a toast.
      console.error('Download failed', err)
    }
  }

  return (
    <div className="content">
      <div className="page-header">
        <div className="page-title">Browse Lessons</div>
        <div className="page-sub">Discover and download learning materials</div>
      </div>
      <div style={{ display: 'flex', gap: 12, marginBottom: 24, flexWrap: 'wrap' }}>
        <div className="search-bar" style={{ maxWidth: 420 }}>
          <i className="ti ti-search" aria-hidden="true" />
          <input
            placeholder={
              filterTeachers && filterModules ? 'Search teachers or modules…' :
              filterTeachers ? 'Search teachers…' :
              filterModules ? 'Search modules…' :
              'Search lessons, teachers, modules…'
            }
            value={search}
            onChange={e => setSearch(e.target.value)}
          />
        </div>
        <button
          type="button"
          onClick={() => setFilterTeachers(v => !v)}
          aria-pressed={filterTeachers}
          style={chipStyle(filterTeachers)}
        >
          <i className="ti ti-school" aria-hidden="true" />
          Teachers
        </button>
        <button
          type="button"
          onClick={() => setFilterModules(v => !v)}
          aria-pressed={filterModules}
          style={chipStyle(filterModules)}
        >
          <i className="ti ti-book-2" aria-hidden="true" />
          Modules
        </button>
        <div className="search-bar" style={{ maxWidth: 220 }}>
          <i className="ti ti-book-2" aria-hidden="true" />
          <input
            placeholder="Filter by module…"
            value={moduleFilter === 'all' ? '' : moduleFilter}
            onChange={e => setModuleFilter(e.target.value || 'all')}
          />
        </div>
      </div>
      {loading ? <div className="spinner spinner-lg" /> : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(300px,1fr))', gap: 16 }}>
          {filtered.map(l => (
            <div key={l.id} className="card" style={{ display: 'flex', flexDirection: 'column', cursor: 'pointer', transition: 'border-color 0.2s' }}
              onClick={() => openLesson(l)}
              onMouseEnter={e => e.currentTarget.style.borderColor = 'var(--gold-border)'}
              onMouseLeave={e => e.currentTarget.style.borderColor = 'var(--border)'}>
              <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 14 }}>
                <div style={{ width: 44, height: 44, borderRadius: 10, background: 'var(--gold-dim)', border: '1px solid var(--gold-border)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20, color: 'var(--gold)', flexShrink: 0 }}>
                  <i className={`ti ${l.fileType === 'PDF' ? 'ti-file-text' : l.fileType === 'DOCX' ? 'ti-file-description' : 'ti-presentation'}`} aria-hidden="true" />
                </div>
                <span className="badge badge-gray">{l.fileType}</span>
              </div>
              <div style={{ fontFamily: "'Playfair Display',serif", fontSize: 17, fontWeight: 500, color: 'var(--text)', marginBottom: 5, lineHeight: 1.3, letterSpacing: '-0.01em' }}>{l.title}</div>
              <div style={{ fontSize: 12, color: 'var(--text3)', marginBottom: 14, letterSpacing: '0.04em' }}>{l.teacher?.firstName} {l.teacher?.lastName}</div>
              <div style={{ display: 'flex', gap: 8, marginBottom: 16, alignItems: 'center', flexWrap: 'wrap' }}>
                <span className="badge badge-neutral">{l.module?.name}</span>
                <span style={{ fontSize: 11, color: 'var(--text3)', letterSpacing: '0.06em', textTransform: 'uppercase', fontWeight: 500 }}>{(l.fileSize / 1024 / 1024).toFixed(1)} MB</span>
              </div>
              <div style={{ display: 'flex', gap: 8, marginTop: 'auto' }} onClick={e => e.stopPropagation()}>
                <button className="btn btn-neutral btn-sm" style={{ flex: 1 }} onClick={e => download(l, e)}>
                  <i className="ti ti-download" aria-hidden="true" />Download
                </button>
                <button className="btn btn-primary btn-sm" style={{ flex: 1 }} onClick={() => openLesson(l)}>
                  <i className="ti ti-message-circle" aria-hidden="true" />Open
                </button>
              </div>
            </div>
          ))}
          {filtered.length === 0 && (
            <div className="empty-state" style={{ gridColumn: '1/-1' }}>
              <i className="ti ti-search-off empty-icon" aria-hidden="true" />
              <div className="empty-text">Nothing matches that. Try a different search.</div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

// ─── LESSON VIEW ─────────────────────────────────────
// The detail page for a single lesson: its info, a download button, and the
// list of approved summaries other students have written for it.
function LessonView({ lesson, setPage }) {
  const { data: summaries } = useFetch(() => summariesAPI.getForLesson(lesson.id), [lesson.id])
  const [openSummary, setOpenSummary] = useState(null)   // a summary opened in the popup (null = none)

  const download = async () => {
    try {
      const res = await lessonsAPI.download(lesson.id)
      const url = URL.createObjectURL(new Blob([res.data]))
      const a = document.createElement('a'); a.href = url
      a.download = `${safeFilename(lesson.title)}.${lesson.fileType.toLowerCase()}`; a.click()
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error('Download failed', err)
    }
  }

  return (
    <div className="content">
      {openSummary && (
        <div style={{ position: 'fixed', inset: 0, background: 'var(--modal-bg)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 300, backdropFilter: 'blur(4px)' }}
          onClick={() => setOpenSummary(null)}>
          <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, padding: 32, width: '100%', maxWidth: 580, maxHeight: '85vh', overflowY: 'auto', position: 'relative' }}
            onClick={e => e.stopPropagation()}>
            <button onClick={() => setOpenSummary(null)} className="modal-close" aria-label="Close"><i className="ti ti-x" aria-hidden="true" /></button>
            <div className="eyebrow" style={{ color: 'var(--gold)', marginBottom: 10 }}>AI Summary</div>
            <div style={{ fontFamily: "'Playfair Display',serif", fontSize: 22, fontWeight: 500, color: 'var(--text)', marginBottom: 16, letterSpacing: '-0.02em' }}>{openSummary.title}</div>
            {openSummary.objectives?.map((o, i) => <div key={i} style={{ fontSize: 13, color: 'var(--text2)', marginBottom: 4 }}>• {o}</div>)}
            {openSummary.keyPoints?.map((kp, i) => (
              <div key={i} style={{ marginTop: 12, padding: '12px 14px', background: 'var(--surface2)', borderRadius: 'var(--radius)', borderLeft: '3px solid var(--gold)' }}>
                <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)', marginBottom: 4 }}>{kp.heading}</div>
                <div style={{ fontSize: 13, color: 'var(--text2)', lineHeight: 1.7 }}>{kp.content}</div>
              </div>
            ))}
            {openSummary.conclusion && <div style={{ marginTop: 14, fontSize: 13, color: 'var(--text2)', fontStyle: 'italic', borderTop: '1px solid var(--border)', paddingTop: 12 }}>{openSummary.conclusion}</div>}
          </div>
        </div>
      )}

      <div style={{ maxWidth: 720 }}>
        <button className="btn btn-neutral btn-sm" style={{ marginBottom: 20 }} onClick={() => setPage('student-browse')}>
          <i className="ti ti-arrow-left" aria-hidden="true" />Back to browse
        </button>
        <div className="card" style={{ marginBottom: 20 }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 16, marginBottom: 20, flexWrap: 'wrap' }}>
            <div style={{ width: 60, height: 60, borderRadius: 12, background: 'var(--gold-dim)', border: '1px solid var(--gold-border)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 26, color: 'var(--gold)', flexShrink: 0 }}>
              <i className={`ti ${lesson.fileType === 'PDF' ? 'ti-file-text' : lesson.fileType === 'DOCX' ? 'ti-file-description' : 'ti-presentation'}`} aria-hidden="true" />
            </div>
            <div style={{ flex: 1 }}>
              <div style={{ fontFamily: "'Playfair Display',serif", fontSize: 24, fontWeight: 500, color: 'var(--text)', marginBottom: 8, lineHeight: 1.25, letterSpacing: '-0.02em' }}>{lesson.title}</div>
              <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                <span className="badge badge-neutral">{lesson.module?.name}</span>
                <span className="badge badge-gray">{lesson.fileType}</span>
              </div>
            </div>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(140px,1fr))', gap: 12, marginBottom: 20 }}>
            {[
              { label: 'Teacher', val: `${lesson.teacher?.firstName} ${lesson.teacher?.lastName}` },
              { label: 'File Size', val: `${(lesson.fileSize / 1024 / 1024).toFixed(1)} MB` },
              { label: 'Uploaded', val: new Date(lesson.createdAt).toLocaleDateString() },
              { label: 'Summaries', val: (summaries || []).length },
            ].map((m, i) => (
              <div key={m.label} style={{ padding: '12px 14px', background: 'var(--surface2)', borderRadius: 10, border: '1px solid var(--border)' }}>
                <div className="eyebrow" style={{ marginBottom: 4 }}>{m.label}</div>
                <div style={{ fontSize: 13.5, fontWeight: 500, color: 'var(--text)' }}>{m.val}</div>
              </div>
            ))}
          </div>
          <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
            <button className="btn btn-primary" onClick={download}>
              <i className="ti ti-download" aria-hidden="true" />Download lesson
            </button>
            <button className="btn btn-ghost" onClick={() => setPage('student-chat')}>
              <i className="ti ti-message-circle" aria-hidden="true" />Chat with this lesson
            </button>
          </div>
        </div>

        <div className="card">
          <div className="section-header" style={{ marginBottom: 16 }}>
            <div className="section-title">Approved Summaries</div>
            <span className="badge badge-success">{(summaries || []).length}</span>
          </div>
          {(summaries || []).length === 0 ? (
            <div className="empty-state">
              <i className="ti ti-notebook empty-icon" aria-hidden="true" />
              <div className="empty-text">Nothing here yet. Use Chat with PDF to draft your first summary.</div>
            </div>
          ) : (summaries || []).map((s) => {
            const parsed = (() => { try { return JSON.parse(s.content) } catch { return null } })()
            return (
              <div key={s.id}
                onClick={() => parsed && setOpenSummary(parsed)}
                style={{ padding: 16, background: 'var(--surface2)', borderRadius: 10, border: '1px solid var(--border)', marginBottom: 10, cursor: 'pointer', transition: 'border-color 0.2s' }}
                onMouseEnter={e => e.currentTarget.style.borderColor = 'var(--gold-border)'}
                onMouseLeave={e => e.currentTarget.style.borderColor = 'var(--border)'}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}>
                  <div style={{ width: 30, height: 30, borderRadius: '50%', background: 'var(--gold)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 11, fontWeight: 500, color: 'var(--surface)', flexShrink: 0, letterSpacing: '0.04em' }}>
                    {s.user?.firstName?.[0]}{s.user?.lastName?.[0]}
                  </div>
                  <span style={{ fontSize: 13, fontWeight: 500, color: 'var(--text)' }}>{s.user?.firstName} {s.user?.lastName}</span>
                  <span className="badge badge-success" style={{ marginLeft: 'auto' }}><i className="ti ti-check" aria-hidden="true" style={{ fontSize: 11 }} />Approved</span>
                </div>
                {parsed?.conclusion && (
                  <div style={{ fontSize: 13, color: 'var(--text2)', lineHeight: 1.65, fontFamily: "'Playfair Display',serif", fontStyle: 'italic' }}>{parsed.conclusion}</div>
                )}
                <div style={{ fontSize: 10, color: 'var(--gold)', marginTop: 10, letterSpacing: '0.12em', textTransform: 'uppercase', fontWeight: 500, display: 'inline-flex', alignItems: 'center', gap: 5 }}>View full summary <i className="ti ti-arrow-right" aria-hidden="true" style={{ fontSize: 11 }} /></div>
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}

// ─── QUIZZES (STUDENT LIST) ──────────────────────────
// Lists the quizzes assigned to the student's filière. Already-taken quizzes
// show the score instead of a Start button.
function StudentQuizzes({ setPage, setSelectedQuizId }) {
  const { user } = useAuth()
  const { data: quizzes, loading } = useFetch(() => quizzesAPI.getAll())

  // A student with no filière can't be assigned quizzes — show a hint instead.
  if (!user?.filiereId) {
    return (
      <div className="content">
        <div className="page-header">
          <div className="page-title">Available Quizzes</div>
          <div className="page-sub">Tests assigned to your filière</div>
        </div>
        <div className="empty-state">
          <i className="ti ti-school empty-icon" aria-hidden="true" />
          <div className="empty-text">
            You haven't been assigned to a filière yet, so no quizzes appear here.
            Please ask an admin to set your filière in your profile.
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="content">
      <div className="page-header">
        <div className="page-title">Available Quizzes</div>
        <div className="page-sub">Tests assigned to your filière</div>
      </div>
      {loading ? <div className="spinner spinner-lg" /> : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(320px,1fr))', gap: 16 }}>
          {(quizzes || []).map(q => {
            const done = !!q.myAttempt
            return (
              <div key={q.id} className="card" style={{ display: 'flex', flexDirection: 'column' }}>
                <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 12 }}>
                  <div style={{ width: 44, height: 44, borderRadius: 10, background: 'var(--gold-dim)', border: '1px solid var(--gold-border)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20, color: 'var(--gold)' }}>
                    <i className="ti ti-checklist" aria-hidden="true" />
                  </div>
                  <span className="badge badge-gray">{q.timeLimit} min</span>
                </div>
                <div style={{ fontFamily: "'Playfair Display',serif", fontSize: 17, fontWeight: 500, color: 'var(--text)', marginBottom: 4, lineHeight: 1.3 }}>{q.title}</div>
                <div style={{ fontSize: 12, color: 'var(--text3)', marginBottom: 10 }}>By {q.teacher?.firstName} {q.teacher?.lastName}</div>
                {q.description && <div style={{ fontSize: 12.5, color: 'var(--text2)', marginBottom: 12, lineHeight: 1.6 }}>{q.description}</div>}
                <div style={{ display: 'flex', gap: 14, fontSize: 11, color: 'var(--text3)', letterSpacing: '0.06em', textTransform: 'uppercase', fontWeight: 500, marginBottom: 14 }}>
                  <span><i className="ti ti-help" aria-hidden="true" /> {q._count?.questions || 0} questions</span>
                </div>
                <div style={{ marginTop: 'auto' }}>
                  {done ? (
                    <div>
                      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 }}>
                        <span style={{ fontSize: 12, color: 'var(--text3)' }}>Your score</span>
                        <span className={`badge ${q.myAttempt.score >= 75 ? 'badge-success' : q.myAttempt.score >= 50 ? 'badge-gold' : 'badge-danger'}`}>{q.myAttempt.score}%</span>
                      </div>
                      <button className="btn btn-neutral btn-sm" disabled style={{ width: '100%' }}>
                        <i className="ti ti-check" aria-hidden="true" />Submitted
                      </button>
                    </div>
                  ) : (
                    <button className="btn btn-primary btn-sm" style={{ width: '100%' }} onClick={() => { setSelectedQuizId(q.id); setPage('student-quiz-take') }}>
                      <i className="ti ti-player-play" aria-hidden="true" />Start quiz
                    </button>
                  )}
                </div>
              </div>
            )
          })}
          {(quizzes || []).length === 0 && (
            <div className="empty-state" style={{ gridColumn: '1/-1' }}>
              <i className="ti ti-checklist empty-icon" aria-hidden="true" />
              <div className="empty-text">No quizzes for your filière yet. Check back later.</div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

// ─── QUIZ TAKE ───────────────────────────────────────
// The timed quiz-taking screen. Renders the questions, runs a countdown timer,
// auto-submits when time runs out, and then shows the score.
function QuizTake({ quizId, setPage }) {
  const { data: quiz, loading } = useFetch(() => quizzesAPI.getById(quizId), [quizId])
  const [answers, setAnswers] = useState({})            // { questionId: chosenChoiceId }
  const [remaining, setRemaining] = useState(null)      // seconds left on the clock
  const [submitting, setSubmitting] = useState(false)
  const [result, setResult] = useState(null)            // the graded result once submitted
  const [error, setError] = useState('')
  const [confirmSubmit, setConfirmSubmit] = useState(false)  // show the "are you sure?" dialog
  const submittedRef = useRef(false)                    // guard so we never submit twice
  // Absolute deadline (timestamp ms). Computed once when the quiz loads.
  // setInterval-based countdowns drift when the tab is backgrounded —
  // anchoring to a Date lets us recover the correct time on every tick.
  const deadlineRef = useRef(null)

  // Once the quiz loads, set the deadline = now + the time limit, and start the clock.
  useEffect(() => {
    if (!quiz || quiz.alreadyAttempted) return
    if (deadlineRef.current == null) {
      deadlineRef.current = Date.now() + quiz.timeLimit * 60 * 1000  // minutes -> milliseconds
      setRemaining(quiz.timeLimit * 60)
    }
  }, [quiz])

  // submit: send the answers and store the graded result.
  // submittedRef makes sure this only ever runs once (manual click OR timeout).
  const submit = async () => {
    if (submittedRef.current) return
    submittedRef.current = true
    setSubmitting(true); setError('')
    try {
      const res = await quizzesAPI.submit(quizId, answers)
      setResult(res.data)
    } catch (err) {
      setError(err.response?.data?.message || 'Submission failed')
      submittedRef.current = false                       // allow a retry on failure
    } finally { setSubmitting(false) }
  }

  // The countdown loop: every half-second, recompute seconds-left from the
  // absolute deadline (robust to the tab being backgrounded). At 0, auto-submit.
  useEffect(() => {
    if (deadlineRef.current == null || result) return
    const tick = () => {
      const left = Math.max(0, Math.ceil((deadlineRef.current - Date.now()) / 1000))
      setRemaining(left)
      if (left <= 0) submit()                            // time's up -> auto-submit
    }
    tick() // immediate sync (no first-second lag)
    const id = setInterval(tick, 500) // every 500ms so backgrounded tabs catch up faster
    return () => clearInterval(id)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [result, quiz])

  // Still loading the quiz? Show a spinner.
  if (loading || !quiz) return <div className="content"><div className="spinner spinner-lg" /></div>

  // The student already took this quiz -> show their previous score, not the questions.
  if (quiz.alreadyAttempted) {
    return (
      <div className="content" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '60vh' }}>
        <div style={{ textAlign: 'center', maxWidth: 420 }}>
          <div style={{ width: 76, height: 76, borderRadius: '50%', background: 'var(--gold-dim)', border: '1px solid var(--gold-border)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 36, color: 'var(--gold)', margin: '0 auto 20px' }}>
            <i className="ti ti-check" aria-hidden="true" />
          </div>
          <div style={{ fontFamily: "'Playfair Display',serif", fontSize: 24, color: 'var(--text)', marginBottom: 8 }}>Already submitted</div>
          <div style={{ fontSize: 14, color: 'var(--text2)', marginBottom: 20 }}>You scored <strong style={{ color: 'var(--gold)' }}>{quiz.myAttempt.score}%</strong> on this quiz.</div>
          <button className="btn btn-primary" onClick={() => setPage('student-quizzes')}>
            <i className="ti ti-arrow-left" aria-hidden="true" />Back to quizzes
          </button>
        </div>
      </div>
    )
  }

  // Submitted -> show the score screen. The circle is drawn with a CSS
  // conic-gradient: pct * 3.6 turns a percentage (0–100) into degrees (0–360).
  if (result) {
    const pct = result.score
    return (
      <div className="content" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '70vh' }}>
        <div style={{ textAlign: 'center', maxWidth: 480 }}>
          <div style={{
            width: 120, height: 120, borderRadius: '50%',
            background: `conic-gradient(var(--gold) ${pct * 3.6}deg, var(--surface2) 0)`,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            margin: '0 auto 24px', position: 'relative',
          }}>
            <div style={{ width: 96, height: 96, borderRadius: '50%', background: 'var(--surface)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'Playfair Display',serif", fontSize: 28, fontWeight: 600, color: 'var(--text)' }}>
              {pct}%
            </div>
          </div>
          <div style={{ fontFamily: "'Playfair Display',serif", fontSize: 28, color: 'var(--text)', marginBottom: 8 }}>
            {pct >= 75 ? <>Excellent <em style={{ color: 'var(--gold)' }}>work</em>.</> : pct >= 50 ? 'Good effort.' : 'Keep practicing.'}
          </div>
          <div style={{ fontSize: 14, color: 'var(--text2)', marginBottom: 24 }}>
            You answered {result.correctCount} out of {result.totalQuestions} questions correctly. Your result has been sent to your teacher.
          </div>
          <button className="btn btn-primary" onClick={() => setPage('student-quizzes')}>
            <i className="ti ti-arrow-left" aria-hidden="true" />Back to quizzes
          </button>
        </div>
      </div>
    )
  }

  // Derived display values for the live quiz view.
  const mins = Math.floor((remaining || 0) / 60)        // whole minutes left
  const secs = (remaining || 0) % 60                    // leftover seconds
  const total = quiz.questions?.length || 0             // total question count
  const answered = Object.keys(answers).length          // how many answered so far
  const urgent = (remaining || 0) <= 60                 // last minute -> turn the timer red

  // The active quiz: a sticky header with title + countdown, then the questions.
  return (
    <div className="content">
      <div style={{
        position: 'sticky', top: 0, zIndex: 5,
        background: 'var(--surface)', borderBottom: '1px solid var(--border)',
        padding: '14px 0', marginBottom: 24,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12,
      }}>
        <div>
          <div style={{ fontFamily: "'Playfair Display',serif", fontSize: 20, fontWeight: 500, color: 'var(--text)' }}>{quiz.title}</div>
          <div style={{ fontSize: 12, color: 'var(--text3)', marginTop: 2 }}>{answered} of {total} answered</div>
        </div>
        <div style={{
          display: 'inline-flex', alignItems: 'center', gap: 8,
          padding: '8px 16px', borderRadius: 10,
          background: urgent ? 'var(--brick-bg)' : 'var(--gold-dim)',
          border: `1px solid ${urgent ? 'var(--brick-border)' : 'var(--gold-border)'}`,
          color: urgent ? 'var(--brick)' : 'var(--gold)',
          fontWeight: 600, fontSize: 14, fontVariantNumeric: 'tabular-nums',
        }}>
          <i className="ti ti-clock" aria-hidden="true" />
          {String(mins).padStart(2, '0')}:{String(secs).padStart(2, '0')}
        </div>
      </div>

      {error && <div className="alert-error" style={{ marginBottom: 16 }}><i className="ti ti-alert-triangle" aria-hidden="true" /><span>{error}</span></div>}

      {(quiz.questions || []).map((q, qi) => (
        <div key={q.id} className="card" style={{ marginBottom: 16 }}>
          <div className="eyebrow" style={{ color: 'var(--gold)', marginBottom: 8 }}>Question {qi + 1} of {total}</div>
          <div style={{ fontSize: 16, color: 'var(--text)', marginBottom: 16, lineHeight: 1.5, fontWeight: 500 }}>{q.text}</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {q.choices.map((c, ci) => {
              const selected = answers[q.id] === c.id
              return (
                <label key={c.id} style={{
                  display: 'flex', alignItems: 'center', gap: 12,
                  padding: '12px 14px', borderRadius: 10, cursor: 'pointer',
                  border: `1px solid ${selected ? 'var(--gold)' : 'var(--border)'}`,
                  background: selected ? 'var(--gold-dim)' : 'transparent',
                  transition: 'all 0.15s',
                }}>
                  <input
                    type="radio"
                    name={`q-${q.id}`}
                    checked={selected}
                    onChange={() => setAnswers(a => ({ ...a, [q.id]: c.id }))}
                    style={{ width: 18, height: 18, accentColor: 'var(--gold)', cursor: 'pointer', flexShrink: 0 }}
                  />
                  <span style={{ fontSize: 14, color: 'var(--text)', flex: 1 }}>
                    <span style={{ fontWeight: 600, marginRight: 8, color: 'var(--text3)' }}>{String.fromCharCode(65 + ci)}.</span>
                    {c.text}
                  </span>
                </label>
              )
            })}
          </div>
        </div>
      ))}

      <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 16 }}>
        <button className="btn btn-primary" onClick={() => setConfirmSubmit(true)} disabled={submitting || answered === 0}>
          {submitting ? <><span className="spinner" />Submitting…</> : <>Submit answers <i className="ti ti-send" aria-hidden="true" /></>}
        </button>
      </div>

      <ConfirmDialog
        open={confirmSubmit}
        title="Submit your answers?"
        message={
          answered < total
            ? `You've answered ${answered} of ${total}. Unanswered questions will be marked wrong. This can't be undone.`
            : `You've answered all ${total} questions. This can't be undone.`
        }
        confirmText="Submit"
        onCancel={() => setConfirmSubmit(false)}
        onConfirm={() => { setConfirmSubmit(false); submit() }}
        busy={submitting}
      />
    </div>
  )
}

// ─── PRACTICE QUIZ — GENERATE FROM A FILE ────────────
// A student drops a PDF/DOCX, the AI drafts questions, and the quiz is saved
// privately to their own page. Nobody else ever sees it.
const PRACTICE_MAX_BYTES = 50 * 1024 * 1024

function PracticeCreate({ setPage }) {
  const [form, setForm] = useState({ title: '', timeLimit: 10, numQuestions: 5 })  // quiz settings
  const [file, setFile] = useState(null)               // the source document
  const [dragging, setDragging] = useState(false)
  const [generating, setGenerating] = useState(false)  // true while the AI drafts questions
  const [saving, setSaving] = useState(false)          // true while saving the finished quiz
  const [error, setError] = useState('')
  const [generated, setGenerated] = useState(null) // { sourceName, questions }  -> the AI's draft
  const fileRef = useRef()

  // Validate a chosen file (PDF/DOCX, size cap) before accepting it.
  const pickFile = (f) => {
    if (!f) return
    const ext = (f.name.split('.').pop() || '').toLowerCase()
    if (!['pdf', 'docx'].includes(ext)) { setError('Please drop a PDF or DOCX file'); return }
    if (f.size > PRACTICE_MAX_BYTES) { setError('File too large (max 50 MB)'); return }
    setError(''); setGenerated(null); setFile(f)
  }

  // generate: upload the file and ask the AI to draft questions (shown for preview).
  const generate = async () => {
    if (!file) { setError('Drop a PDF or DOCX file first'); return }
    setGenerating(true); setError('')
    try {
      const fd = new FormData()
      fd.append('file', file)
      fd.append('numQuestions', String(form.numQuestions))
      if (form.title.trim()) fd.append('title', form.title.trim())
      const res = await quizzesAPI.generate(fd)
      const questions = res.data.questions || []
      if (questions.length === 0) { setError('The AI could not build questions from that file. Try another document.'); return }
      setGenerated({ sourceName: res.data.sourceName, questions })
      if (!form.title.trim() && res.data.title) setForm(f => ({ ...f, title: res.data.title }))
    } catch (err) {
      setError(err.response?.data?.message || 'Generation failed. Please try again.')
    } finally { setGenerating(false) }
  }

  // save: store the AI-drafted questions as a private practice quiz.
  const save = async () => {
    if (!generated) return
    if (!form.title.trim()) { setError('Give your quiz a title'); return }
    setSaving(true); setError('')
    try {
      await practiceQuizzesAPI.create({
        title: form.title.trim(),
        timeLimit: Number(form.timeLimit),
        questions: generated.questions,
        sourceName: generated.sourceName,
      })
      setPage('student-practice')
    } catch (err) {
      setError(err.response?.data?.message || 'Could not save your quiz')
    } finally { setSaving(false) }
  }

  return (
    <div className="content">
      <button className="btn btn-neutral btn-sm" style={{ marginBottom: 20 }} onClick={() => setPage('student-practice')}>
        <i className="ti ti-arrow-left" aria-hidden="true" />Back to my practice quizzes
      </button>
      <div className="page-header">
        <div className="page-title">New Practice Quiz</div>
        <div className="page-sub">Drop a document and the AI turns it into a quiz only you can see.</div>
      </div>

      {error && <div className="alert-error" style={{ marginBottom: 16 }}><i className="ti ti-alert-triangle" aria-hidden="true" /><span>{error}</span></div>}

      <div style={{ maxWidth: 720 }}>
        <div className="card" style={{ marginBottom: 20 }}>
          {/* File drop zone */}
          <div
            onDragOver={e => { e.preventDefault(); setDragging(true) }}
            onDragLeave={() => setDragging(false)}
            onDrop={e => { e.preventDefault(); setDragging(false); pickFile(e.dataTransfer.files?.[0]) }}
            onClick={() => fileRef.current.click()}
            style={{ border: `2px dashed ${dragging ? 'var(--gold)' : 'var(--border)'}`, borderRadius: 'var(--radius-lg)', padding: '32px 24px', textAlign: 'center', cursor: 'pointer', transition: 'all 0.2s', background: dragging ? 'var(--gold-dim)' : 'var(--surface2)' }}
          >
            {file ? (
              <div>
                <i className="ti ti-file-text" aria-hidden="true" style={{ fontSize: 34, color: 'var(--gold)', display: 'block', marginBottom: 10 }} />
                <div style={{ fontSize: 14, fontWeight: 500, color: 'var(--text)' }}>{file.name}</div>
                <div style={{ fontSize: 11, color: 'var(--text3)', marginTop: 5, letterSpacing: '0.06em', textTransform: 'uppercase', fontWeight: 500 }}>{(file.size / 1024 / 1024).toFixed(2)} MB</div>
                <button className="btn btn-neutral btn-sm" style={{ marginTop: 12 }} onClick={e => { e.stopPropagation(); setFile(null); setGenerated(null) }}>
                  <i className="ti ti-x" aria-hidden="true" />Remove
                </button>
              </div>
            ) : (
              <div>
                <i className="ti ti-cloud-upload" aria-hidden="true" style={{ fontSize: 36, color: 'var(--icon)', display: 'block', marginBottom: 12 }} />
                <div style={{ fontSize: 14, fontWeight: 500, color: 'var(--text)', marginBottom: 6 }}>Drop your PDF or DOCX here, or click to browse</div>
                <div style={{ fontSize: 11, color: 'var(--text3)', letterSpacing: '0.08em', textTransform: 'uppercase', fontWeight: 500 }}>PDF, DOCX — up to 50 MB</div>
              </div>
            )}
          </div>
          <input ref={fileRef} type="file" style={{ display: 'none' }} accept=".pdf,.docx" onChange={e => pickFile(e.target.files?.[0])} />

          <div className="two-col" style={{ marginTop: 16 }}>
            <div className="field" style={{ marginBottom: 0 }}>
              <label className="field-label">Number of questions</label>
              <input className="field-input" type="number" min="1" max="20" value={form.numQuestions}
                onChange={e => setForm(f => ({ ...f, numQuestions: Math.max(1, Math.min(20, Number(e.target.value) || 1)) }))} />
            </div>
            <div className="field" style={{ marginBottom: 0 }}>
              <label className="field-label">Time limit (minutes)</label>
              <input className="field-input" type="number" min="1" value={form.timeLimit}
                onChange={e => setForm(f => ({ ...f, timeLimit: Math.max(1, Number(e.target.value) || 1) }))} />
            </div>
          </div>
          <div className="field" style={{ marginTop: 16, marginBottom: 0 }}>
            <label className="field-label">Title</label>
            <input className="field-input" value={form.title} onChange={e => setForm(f => ({ ...f, title: e.target.value }))} placeholder="Auto-filled from the file name — edit if you like" />
          </div>

          <button className="btn btn-primary" style={{ width: '100%', marginTop: 18 }} onClick={generate} disabled={generating || !file}>
            {generating ? <><span className="spinner" />Generating…</> : <><i className="ti ti-sparkles" aria-hidden="true" />{generated ? 'Regenerate questions' : 'Generate questions'}</>}
          </button>
          {generating && <div style={{ fontSize: 12, color: 'var(--text3)', marginTop: 10, textAlign: 'center' }}>Reading your document and writing questions — this can take up to a minute.</div>}
        </div>

        {/* Preview (answers hidden so the quiz is still worth taking) */}
        {generated && (
          <div className="card">
            <div className="section-header" style={{ marginBottom: 14 }}>
              <div className="section-title">{generated.questions.length} question{generated.questions.length !== 1 ? 's' : ''} ready</div>
              <span className="badge badge-gold"><i className="ti ti-eye-off" aria-hidden="true" style={{ fontSize: 11 }} />Answers hidden</span>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginBottom: 18 }}>
              {generated.questions.map((q, qi) => (
                <div key={qi} style={{ padding: '14px 16px', background: 'var(--surface2)', borderRadius: 'var(--radius)', border: '1px solid var(--border)' }}>
                  <div style={{ fontSize: 13.5, fontWeight: 500, color: 'var(--text)', marginBottom: 8 }}>{qi + 1}. {q.text}</div>
                  <div style={{ display: 'grid', gap: 4 }}>
                    {q.choices.map((c, ci) => (
                      <div key={ci} style={{ fontSize: 12.5, color: 'var(--text2)' }}>
                        <span style={{ fontWeight: 600, color: 'var(--text3)', marginRight: 6 }}>{String.fromCharCode(65 + ci)}.</span>{c.text}
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
            <button className="btn btn-primary" style={{ width: '100%' }} onClick={save} disabled={saving}>
              {saving ? <><span className="spinner" />Saving…</> : <><i className="ti ti-device-floppy" aria-hidden="true" />Save to my practice quizzes</>}
            </button>
          </div>
        )}
      </div>
    </div>
  )
}

// ─── PRACTICE QUIZ — MY LIST ─────────────────────────
// A grid of the student's saved practice quizzes, with start/retake and delete.
function StudentPractice({ setPage, setSelectedPracticeId }) {
  const { data: quizzes, loading, refetch } = useFetch(() => practiceQuizzesAPI.getMy())
  const [confirmDel, setConfirmDel] = useState(null)
  const [toast, setToast] = useState(null)
  const showToast = (msg, ok = true) => { setToast({ msg, ok }); setTimeout(() => setToast(null), 3000) }

  const doDelete = async () => {
    const q = confirmDel
    if (!q) return
    try {
      await practiceQuizzesAPI.delete(q.id); refetch()
      showToast('Practice quiz deleted')
    } catch (err) {
      showToast(err.response?.data?.message || 'Failed to delete', false)
    } finally { setConfirmDel(null) }
  }

  return (
    <div className="content">
      <div className="page-header">
        <div className="page-title">My Practice Quizzes</div>
        <div className="page-sub">Private quizzes you generated from your own documents</div>
      </div>
      <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 24 }}>
        <button className="btn btn-primary" onClick={() => setPage('student-practice-create')}>
          <i className="ti ti-sparkles" aria-hidden="true" />New practice quiz
        </button>
      </div>
      {loading ? <div className="spinner spinner-lg" /> : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(320px,1fr))', gap: 16 }}>
          {(quizzes || []).map(q => (
            <div key={q.id} className="card" style={{ display: 'flex', flexDirection: 'column' }}>
              <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 12 }}>
                <div style={{ width: 44, height: 44, borderRadius: 10, background: 'var(--gold-dim)', border: '1px solid var(--gold-border)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20, color: 'var(--gold)' }}>
                  <i className="ti ti-sparkles" aria-hidden="true" />
                </div>
                <span className="badge badge-gray">{q.timeLimit} min</span>
              </div>
              <div style={{ fontFamily: "'Playfair Display',serif", fontSize: 17, fontWeight: 500, color: 'var(--text)', marginBottom: 4, lineHeight: 1.3 }}>{q.title}</div>
              {q.sourceName && <div style={{ fontSize: 11.5, color: 'var(--text3)', marginBottom: 10, display: 'flex', alignItems: 'center', gap: 5, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}><i className="ti ti-file" aria-hidden="true" />{q.sourceName}</div>}
              <div style={{ display: 'flex', gap: 14, fontSize: 11, color: 'var(--text3)', letterSpacing: '0.06em', textTransform: 'uppercase', fontWeight: 500, marginBottom: 14 }}>
                <span><i className="ti ti-help" aria-hidden="true" /> {q.questionCount} questions</span>
              </div>
              <div style={{ marginTop: 'auto' }}>
                {q.lastAttempt && (
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
                    <span style={{ fontSize: 12, color: 'var(--text3)' }}>Last score</span>
                    <span className={`badge ${q.lastAttempt.score >= 75 ? 'badge-success' : q.lastAttempt.score >= 50 ? 'badge-gold' : 'badge-danger'}`}>{q.lastAttempt.score}%</span>
                  </div>
                )}
                <div style={{ display: 'flex', gap: 8 }}>
                  <button className="btn btn-primary btn-sm" style={{ flex: 1 }} onClick={() => { setSelectedPracticeId(q.id); setPage('student-practice-take') }}>
                    <i className={`ti ${q.lastAttempt ? 'ti-rotate' : 'ti-player-play'}`} aria-hidden="true" />{q.lastAttempt ? 'Retake' : 'Start'}
                  </button>
                  <button className="btn btn-danger btn-sm" onClick={() => setConfirmDel(q)} aria-label="Delete practice quiz">
                    <i className="ti ti-trash" aria-hidden="true" />
                  </button>
                </div>
              </div>
            </div>
          ))}
          {(quizzes || []).length === 0 && (
            <div className="empty-state" style={{ gridColumn: '1/-1' }}>
              <i className="ti ti-sparkles empty-icon" aria-hidden="true" />
              <div className="empty-text">No practice quizzes yet. Drop a document to generate your first one.</div>
            </div>
          )}
        </div>
      )}

      <ConfirmDialog
        open={!!confirmDel}
        title="Delete this practice quiz?"
        message={confirmDel ? `"${confirmDel.title}" will be permanently removed.` : ''}
        confirmText="Delete"
        danger
        onCancel={() => setConfirmDel(null)}
        onConfirm={doDelete}
      />
      {toast && <div className={`toast ${toast.ok ? 'toast-ok' : 'toast-err'}`} role="status"><i className={`ti ${toast.ok ? 'ti-check' : 'ti-alert-triangle'}`} aria-hidden="true" /><span>{toast.msg}</span></div>}
    </div>
  )
}

// ─── PRACTICE QUIZ — TAKE ────────────────────────────
// Almost identical to QuizTake, but for a private practice quiz. Extra perk:
// after submitting, it shows a full answer review (which choice was correct).
function PracticeTake({ practiceId, setPage }) {
  const { data: quiz, loading } = useFetch(() => practiceQuizzesAPI.getById(practiceId), [practiceId])
  const [answers, setAnswers] = useState({})
  const [remaining, setRemaining] = useState(null)
  const [submitting, setSubmitting] = useState(false)
  const [result, setResult] = useState(null)
  const [error, setError] = useState('')
  const [confirmSubmit, setConfirmSubmit] = useState(false)
  const submittedRef = useRef(false)
  const deadlineRef = useRef(null)

  useEffect(() => {
    if (!quiz) return
    if (deadlineRef.current == null) {
      deadlineRef.current = Date.now() + quiz.timeLimit * 60 * 1000
      setRemaining(quiz.timeLimit * 60)
    }
  }, [quiz])

  const submit = async () => {
    if (submittedRef.current) return
    submittedRef.current = true
    setSubmitting(true); setError('')
    try {
      const res = await practiceQuizzesAPI.submit(practiceId, answers)
      setResult(res.data)
    } catch (err) {
      setError(err.response?.data?.message || 'Submission failed')
      submittedRef.current = false
    } finally { setSubmitting(false) }
  }

  useEffect(() => {
    if (deadlineRef.current == null || result) return
    const tick = () => {
      const left = Math.max(0, Math.ceil((deadlineRef.current - Date.now()) / 1000))
      setRemaining(left)
      if (left <= 0) submit()
    }
    tick()
    const id = setInterval(tick, 500)
    return () => clearInterval(id)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [result, quiz])

  if (loading || !quiz) return <div className="content"><div className="spinner spinner-lg" /></div>

  if (result) {
    const pct = result.score
    const reviewByIndex = Object.fromEntries((result.review || []).map(r => [r.index, r]))
    return (
      <div className="content">
        <div style={{ textAlign: 'center', maxWidth: 480, margin: '0 auto 32px' }}>
          <div style={{
            width: 120, height: 120, borderRadius: '50%',
            background: `conic-gradient(var(--gold) ${pct * 3.6}deg, var(--surface2) 0)`,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            margin: '0 auto 24px',
          }}>
            <div style={{ width: 96, height: 96, borderRadius: '50%', background: 'var(--surface)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'Playfair Display',serif", fontSize: 28, fontWeight: 600, color: 'var(--text)' }}>
              {pct}%
            </div>
          </div>
          <div style={{ fontFamily: "'Playfair Display',serif", fontSize: 28, color: 'var(--text)', marginBottom: 8 }}>
            {pct >= 75 ? <>Well <em style={{ color: 'var(--gold)' }}>done</em>.</> : pct >= 50 ? 'Good effort.' : 'Keep practicing.'}
          </div>
          <div style={{ fontSize: 14, color: 'var(--text2)', marginBottom: 20 }}>
            You answered {result.correctCount} out of {result.totalQuestions} correctly.
          </div>
          <div style={{ display: 'flex', gap: 10, justifyContent: 'center', flexWrap: 'wrap' }}>
            <button className="btn btn-neutral" onClick={() => setPage('student-practice')}>
              <i className="ti ti-arrow-left" aria-hidden="true" />Back to my quizzes
            </button>
            <button className="btn btn-primary" onClick={() => { submittedRef.current = false; deadlineRef.current = null; setAnswers({}); setResult(null) }}>
              <i className="ti ti-rotate" aria-hidden="true" />Retake
            </button>
          </div>
        </div>

        {/* Answer review */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          {(quiz.questions || []).map((q, qi) => {
            const rv = reviewByIndex[q.index]
            return (
              <div key={q.index} className="card">
                <div style={{ display: 'flex', alignItems: 'flex-start', gap: 8, marginBottom: 12 }}>
                  <i className={`ti ${rv?.isCorrect ? 'ti-circle-check' : 'ti-circle-x'}`} aria-hidden="true" style={{ fontSize: 18, color: rv?.isCorrect ? 'var(--green)' : 'var(--red)', marginTop: 2, flexShrink: 0 }} />
                  <div style={{ fontSize: 15, color: 'var(--text)', fontWeight: 500, lineHeight: 1.5 }}>{qi + 1}. {q.text}</div>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {q.choices.map((c, ci) => {
                    const isCorrect = rv && ci === rv.correctIndex
                    const isChosenWrong = rv && ci === rv.chosenIndex && ci !== rv.correctIndex
                    return (
                      <div key={c.index} style={{
                        display: 'flex', alignItems: 'center', gap: 10,
                        padding: '10px 12px', borderRadius: 9, fontSize: 13.5,
                        border: `1px solid ${isCorrect ? 'var(--green)' : isChosenWrong ? 'var(--red)' : 'var(--border)'}`,
                        background: isCorrect ? 'var(--green-bg, var(--gold-dim))' : isChosenWrong ? 'var(--brick-bg)' : 'transparent',
                        color: 'var(--text)',
                      }}>
                        <span style={{ fontWeight: 600, color: 'var(--text3)' }}>{String.fromCharCode(65 + ci)}.</span>
                        <span style={{ flex: 1 }}>{c.text}</span>
                        {isCorrect && <span className="badge badge-success"><i className="ti ti-check" aria-hidden="true" style={{ fontSize: 11 }} />Correct</span>}
                        {isChosenWrong && <span className="badge badge-danger">Your answer</span>}
                      </div>
                    )
                  })}
                  {rv && rv.chosenIndex == null && (
                    <div style={{ fontSize: 12, color: 'var(--text3)', fontStyle: 'italic' }}>You didn't answer this question.</div>
                  )}
                </div>
              </div>
            )
          })}
        </div>
      </div>
    )
  }

  const mins = Math.floor((remaining || 0) / 60)
  const secs = (remaining || 0) % 60
  const total = quiz.questions?.length || 0
  const answered = Object.keys(answers).length
  const urgent = (remaining || 0) <= 60

  return (
    <div className="content">
      <div style={{
        position: 'sticky', top: 0, zIndex: 5,
        background: 'var(--surface)', borderBottom: '1px solid var(--border)',
        padding: '14px 0', marginBottom: 24,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12,
      }}>
        <div>
          <div style={{ fontFamily: "'Playfair Display',serif", fontSize: 20, fontWeight: 500, color: 'var(--text)' }}>{quiz.title}</div>
          <div style={{ fontSize: 12, color: 'var(--text3)', marginTop: 2 }}>{answered} of {total} answered · private practice quiz</div>
        </div>
        <div style={{
          display: 'inline-flex', alignItems: 'center', gap: 8,
          padding: '8px 16px', borderRadius: 10,
          background: urgent ? 'var(--brick-bg)' : 'var(--gold-dim)',
          border: `1px solid ${urgent ? 'var(--brick-border)' : 'var(--gold-border)'}`,
          color: urgent ? 'var(--brick)' : 'var(--gold)',
          fontWeight: 600, fontSize: 14, fontVariantNumeric: 'tabular-nums',
        }}>
          <i className="ti ti-clock" aria-hidden="true" />
          {String(mins).padStart(2, '0')}:{String(secs).padStart(2, '0')}
        </div>
      </div>

      {error && <div className="alert-error" style={{ marginBottom: 16 }}><i className="ti ti-alert-triangle" aria-hidden="true" /><span>{error}</span></div>}

      {(quiz.questions || []).map((q, qi) => (
        <div key={q.index} className="card" style={{ marginBottom: 16 }}>
          <div className="eyebrow" style={{ color: 'var(--gold)', marginBottom: 8 }}>Question {qi + 1} of {total}</div>
          <div style={{ fontSize: 16, color: 'var(--text)', marginBottom: 16, lineHeight: 1.5, fontWeight: 500 }}>{q.text}</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {q.choices.map((c, ci) => {
              const selected = answers[q.index] === c.index
              return (
                <label key={c.index} style={{
                  display: 'flex', alignItems: 'center', gap: 12,
                  padding: '12px 14px', borderRadius: 10, cursor: 'pointer',
                  border: `1px solid ${selected ? 'var(--gold)' : 'var(--border)'}`,
                  background: selected ? 'var(--gold-dim)' : 'transparent',
                  transition: 'all 0.15s',
                }}>
                  <input
                    type="radio"
                    name={`pq-${q.index}`}
                    checked={selected}
                    onChange={() => setAnswers(a => ({ ...a, [q.index]: c.index }))}
                    style={{ width: 18, height: 18, accentColor: 'var(--gold)', cursor: 'pointer', flexShrink: 0 }}
                  />
                  <span style={{ fontSize: 14, color: 'var(--text)', flex: 1 }}>
                    <span style={{ fontWeight: 600, marginRight: 8, color: 'var(--text3)' }}>{String.fromCharCode(65 + ci)}.</span>
                    {c.text}
                  </span>
                </label>
              )
            })}
          </div>
        </div>
      ))}

      <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 16, gap: 12, flexWrap: 'wrap' }}>
        <button className="btn btn-neutral" onClick={() => setPage('student-practice')}>
          <i className="ti ti-arrow-left" aria-hidden="true" />Quit
        </button>
        <button className="btn btn-primary" onClick={() => setConfirmSubmit(true)} disabled={submitting || answered === 0}>
          {submitting ? <><span className="spinner" />Submitting…</> : <>Submit answers <i className="ti ti-send" aria-hidden="true" /></>}
        </button>
      </div>

      <ConfirmDialog
        open={confirmSubmit}
        title="Submit your answers?"
        message={
          answered < total
            ? `You've answered ${answered} of ${total}. Unanswered questions will be marked wrong.`
            : `You've answered all ${total} questions.`
        }
        confirmText="Submit"
        onCancel={() => setConfirmSubmit(false)}
        onConfirm={() => { setConfirmSubmit(false); submit() }}
        busy={submitting}
      />
    </div>
  )
}

// ─── ROOT ────────────────────────────────────────────
// Top-level student component: sets up the frame, holds the "which item is
// selected" state shared between pages, and renders the active sub-page.

// Tab id -> title shown in the top bar.
const PAGE_TITLES = {
  'student-dash':       'Dashboard',
  'student-browse':     'Browse Lessons',
  'student-lesson':     'Lesson View',
  'student-summaries':  'My Summaries',
  'student-chat':       'Chat with PDF',
  'student-quizzes':    'Quizzes',
  'student-quiz-take':  'Take Quiz',
  'student-practice':         'Practice Quiz',
  'student-practice-create':  'New Practice Quiz',
  'student-practice-take':    'Practice Quiz',
}

export default function StudentDashboard() {
  const { user } = useAuth()
  const [page, setPage] = useHashPage('student-dash')               // active tab (saved in the URL)
  // "Which item did the user pick?" — carried between pages (e.g. browse -> view).
  const [selectedLesson, setSelectedLesson] = useState(null)
  const [selectedQuizId, setSelectedQuizId] = useState(null)
  const [selectedPracticeId, setSelectedPracticeId] = useState(null)
  const [sidebarOpen, setSidebarOpen] = useState(false)            // mobile drawer
  const { data: lessons } = useFetch(() => lessonsAPI.getAll())    // data for the home dashboard
  const { data: summaries } = useFetch(() => summariesAPI.getMy())

  // Pick the sub-page component for the current tab (some need a selected item).
  const renderPage = () => {
    if (page === 'student-browse')    return <BrowseLessons setPage={setPage} setSelectedLesson={setSelectedLesson} />
    if (page === 'student-lesson' && selectedLesson) return <LessonView lesson={selectedLesson} setPage={setPage} />
    if (page === 'student-summaries') return <MySummaries />
    if (page === 'student-chat')      return <ChatPage role="STUDENT" preselectedLesson={selectedLesson} />
    if (page === 'student-quizzes')   return <StudentQuizzes setPage={setPage} setSelectedQuizId={setSelectedQuizId} />
    if (page === 'student-quiz-take' && selectedQuizId) return <QuizTake quizId={selectedQuizId} setPage={setPage} />
    if (page === 'student-practice')         return <StudentPractice setPage={setPage} setSelectedPracticeId={setSelectedPracticeId} />
    if (page === 'student-practice-create')  return <PracticeCreate setPage={setPage} />
    if (page === 'student-practice-take' && selectedPracticeId) return <PracticeTake practiceId={selectedPracticeId} setPage={setPage} />
    return <StudentHome setPage={setPage} lessons={lessons} summaries={summaries} firstName={user?.firstName} />
  }

  return (
    <div className="layout">
      <Sidebar role={user?.role} page={page} setPage={setPage} open={sidebarOpen} onClose={() => setSidebarOpen(false)} />
      <div className="main">
        <Topbar title={PAGE_TITLES[page] || 'Dashboard'} onMenuToggle={() => setSidebarOpen(v => !v)} />
        {renderPage()}
      </div>
    </div>
  )
}
